# Lightweight docker-compose for low resource systems

services:
  backend:
    build: ./wisetale-api
    container_name: wisetale-backend
    env_file:
      - ./wisetale-api/.env
    ports:
      - "8000:8000"
    volumes:
      - ./wisetale-api:/app
    environment:
      - REDIS_URL=redis://localhost:6379  # Will be ignored if no Redis

  frontend:
    build: ./wisetale-app
    container_name: wisetale-frontend
    ports:
      - "3001:3001"
    volumes:
      - ./wisetale-app:/app
    command: npm run dev 