services:
  backend:
    build:
      context: ./wizetale-api
    container_name: wizetale-backend-prod
    env_file:
      - ./wizetale-api/.env
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - wizetale_net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-prod.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    networks:
      - wizetale_net

  redis:
    image: redis:alpine
    container_name: wizetale-redis-prod
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - wizetale_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:

networks:
  wizetale_net:
    driver: bridge 