# docker-compose for WiseTale full stack

services:
  backend:
    build: 
      context: ./wisetale-api
      target: base
    container_name: wisetale-backend
    env_file:
      - ./wisetale-api/.env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./wisetale-api:/app

  frontend:
    build: 
      context: ./wisetale-app
      target: dev
    container_name: wisetale-frontend
    ports:
      - "3001:3001"
    volumes:
      - ./wisetale-app:/app
    command: npm run dev

  landing:
    build: 
      context: ./wisetale-landing
      target: dev
    container_name: wisetale-landing
    ports:
      - "3000:3000"
    volumes:
      - ./wisetale-landing:/app
    command: npm run dev

  redis:
    image: redis:7-alpine
    container_name: wisetale-redis
    ports:
      - "6379:6379" 