# Ultra-fast development docker-compose with BuildKit optimization
# Uses multi-stage builds, cache mounts, and dev targets for maximum speed

services:
  backend:
    build:
      context: ./wisetale-api
      target: dev  # Use dev stage with hot reload
    image: wisetale-backend:dev  # Tag for better cache reuse
    container_name: wisetale-backend-dev
    command: sh -c ". .venv/bin/activate && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - ./wisetale-api/.env
    ports:
      - "8000:8000"
    volumes:
      # Mount the application code
      - ./wisetale-api/app:/app/app
      # Mount the firebase credentials
      - ./wisetale-api/time-capsule-d5a66-c542dacf194a.json:/app/time-capsule-d5a66-c542dacf194a.json:ro
      # Preserve the virtual environment from the build
      - backend_venv:/app/.venv
      # Mount specific config files for hot reload
      - ./wisetale-api/pyproject.toml:/app/pyproject.toml:ro
    environment:
      - VIRTUAL_ENV=/app/.venv
      - PATH=/app/.venv/bin:$PATH
    depends_on:
      - redis
    networks:
      - wisetale_net

  redis:
    image: redis:7.2-alpine
    container_name: wisetale-redis-dev
    ports:
      - "6380:6379"
    # volumes:
    #   - redis-data:/data
    restart: unless-stopped
    healthcheck:
      disable: true
    networks:
      - wisetale_net

  celery_worker:
    build:
      context: ./wisetale-api
    image: wisetale-backend:dev
    container_name: wisetale-celery-worker-dev
    command: sh -c ". .venv/bin/activate && celery -A worker.celery_app worker -l info"
    env_file:
      - ./wisetale-api/.env
    volumes:
      - ./wisetale-api/app:/app/app
      - ./wisetale-api/time-capsule-d5a66-c542dacf194a.json:/app/time-capsule-d5a66-c542dacf194a.json:ro
      - backend_venv:/app/.venv
    environment:
      - VIRTUAL_ENV=/app/.venv
      - PATH=/app/.venv/bin:$PATH
    depends_on:
      - backend
      - redis
    networks:
      - wisetale_net

  frontend:
    build:
      context: ./wisetale-app
      target: dev  # Use dev stage
    image: wisetale-frontend:dev  # Tag for better cache reuse
    container_name: wisetale-frontend-dev
    ports:
      - "3001:3001"
    environment: []
    networks:
      - wisetale_net

volumes:
  backend_venv:
    driver: local
  redis-data:
    driver: local

networks:
  wisetale_net:
    driver: bridge 