# docker-compose for Wizetale full stack

services:
  backend:
    build:
      context: ./wizetale-api
      target: dev
    container_name: wizetale-backend
    env_file:
      - ./wizetale-api/.env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: .venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./wizetale-api:/app
      - /app/.venv

  frontend:
    build: 
      context: ./wizetale-app
      target: dev
    container_name: wizetale-frontend
    ports:
      - "3001:3001"
    volumes:
      - ./wizetale-app:/app
    command: npm run dev

  celery-worker:
    image: wizetale-backend
    build:
      context: ./wizetale-api
      target: dev
    volumes:
      - ./wizetale-api:/app
      - /app/.venv
    env_file:
      - ./wizetale-api/.env
    depends_on:
      - redis
    command: .venv/bin/celery -A app.celery_utils.celery_app worker --loglevel=info

  redis:
    image: "redis:7-alpine"
    container_name: wizetale-redis
    ports:
      - "6380:6379" 