# Ultra-fast development docker-compose with BuildKit optimization
# Uses multi-stage builds, cache mounts, and dev targets for maximum speed

services:
  backend:
    build:
      context: ./wizetale-api
      dockerfile: Dockerfile
      target: dev  # Use dev stage with hot reload
    image: wizetale-backend:dev  # Tag for better cache reuse
    container_name: wizetale-backend-dev
    command: sh -c ". .venv/bin/activate && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - ./wizetale-api/.env
    ports:
      - "8000:8000"
    volumes:
      # Mount the application code
      - ./wizetale-api/app:/app/app
      # For local dev, mount generated files to inspect them
      - ./wizetale-api/generated_images:/app/generated_images
      - ./wizetale-api/generated_videos:/app/generated_videos
      # Mount the firebase credentials
      - ./wizetale-api/time-capsule-d5a66-c542dacf194a.json:/app/time-capsule-d5a66-c542dacf194a.json:ro
      # Preserve the virtual environment from the build
      - backend_venv:/app/.venv
      # Mount specific config files for hot reload
      - ./wizetale-api/pyproject.toml:/app/pyproject.toml:ro
    environment:
      - VIRTUAL_ENV=/app/.venv
      - PATH=/app/.venv/bin:$PATH
    depends_on:
      - redis
    networks:
      - wizetale_net

  redis:
    image: redis:7.2-alpine
    container_name: wizetale-redis-dev
    ports:
      - "6380:6379"
    # volumes:
    #   - redis-data:/data
    restart: unless-stopped
    healthcheck:
      disable: true
    networks:
      - wizetale_net

  celery_worker:
    build:
      context: ./wizetale-api
      dockerfile: Dockerfile
    image: wizetale-backend:dev
    container_name: wizetale-celery-worker-dev
    command: celery -A worker.celery_app worker --loglevel=info -P gevent -c 4
    env_file:
      - ./wizetale-api/.env
    volumes:
      - ./wizetale-api/app:/app/app
      - ./wizetale-api/time-capsule-d5a66-c542dacf194a.json:/app/time-capsule-d5a66-c542dacf194a.json:ro
      - ./wizetale-api/generated_images:/app/generated_images
      - ./wizetale-api/generated_videos:/app/generated_videos
      - ./wizetale-api/generated_audio:/app/generated_audio
    environment:
      - VIRTUAL_ENV=/app/.venv
      - PATH=/app/.venv/bin:$PATH
    depends_on:
      - backend
      - redis
    networks:
      - wizetale_net

  frontend:
    build:
      context: ./wizetale-app
      dockerfile: Dockerfile
      target: dev  # Use dev stage
    image: wizetale-frontend:dev  # Tag for better cache reuse
    container_name: wizetale-frontend-dev
    ports:
      - "3001:3001"
    environment: []
    networks:
      - wizetale_net

volumes:
  backend_venv:
    driver: local
  redis-data:
    driver: local

networks:
  wizetale_net:
    driver: bridge 